export type ExampleImage = {
  image: number
  credit?: string
  name: string
  label: "neutral" | "borderline-sfw" | "drawing"
  licensePlate: boolean
  face: boolean
  knownObject?: boolean
}

export const exampleImages: ExampleImage[] = [
  {
    image: require("./face-detection/kevin-seibel-oo6XOGrSyX8-unsplash.jpg"),
    credit: "Photo by Kevin Seibel on Unsplash",
    name: "kevin-seibel-oo6XOGrSyX8-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./face-detection/neom-207NEuFvjlg-unsplash.jpg"),
    credit: "Photo by NEOM on Unsplash",
    name: "neom-207NEuFvjlg-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./face-detection/denis-kirichkov-PVQcdxcFxfQ-unsplash.jpg"),
    credit: "Photo by Denis Kirichkov on Unsplash",
    name: "denis-kirichkov-PVQcdxcFxfQ-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./face-detection/stas-ostrikov-bgprFTkBIyU-unsplash.jpg"),
    credit: "Photo by Stas Ostrikov on Unsplash",
    name: "stas-ostrikov-bgprFTkBIyU-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./face-detection/justus-menke-s2OisyY9YGU-unsplash.jpg"),
    credit: "Photo by Justus Menke on Unsplash",
    name: "justus-menke-s2OisyY9YGU-unsplash",
    label: "neutral",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./face-detection/boxed-water-is-better-WbpsINKjB9Y-unsplash.jpg"),
    credit: "Photo by Boxed Water Is Better on Unsplash",
    name: "boxed-water-is-better-WbpsINKjB9Y-unsplash",
    label: "neutral",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./face-detection/nicholas-green-nPz8akkUmDI-unsplash.jpg"),
    credit: "Photo by Nicholas Green on Unsplash",
    name: "nicholas-green-nPz8akkUmDI-unsplash",
    label: "neutral",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./face-detection/naassom-azevedo-Q_Sei-TqSlc-unsplash.jpg"),
    credit: "Photo by Naassom Azevedo on Unsplash",
    name: "naassom-azevedo-Q_Sei-TqSlc-unsplash",
    label: "neutral",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./image-labeling/neutral/hiki-app-eLbOPPiDehA-unsplash.jpg"),
    credit: "Hiki App on Unsplash",
    name: "hiki-app-eLbOPPiDehA-unsplash",
    label: "neutral",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./image-labeling/neutral/zo-razafindramamba-8FEkr9X631Q-unsplash.jpg"),
    credit: "Zo Razafindramamba on Unsplash",
    name: "zo-razafindramamba-8FEkr9X631Q-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/neutral/tian-dayong-uf-h_PC2lY0-unsplash.jpg"),
    credit: "Tian Dayong on Unsplash",
    name: "tian-dayong-uf-h_PC2lY0-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/neutral/filippo-H2eQ2JZc4ww-unsplash.jpg"),
    credit: "Filippo on Unsplash",
    name: "filippo-H2eQ2JZc4ww-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/neutral/mike-cox-fj0p1NDAQHA-unsplash.jpg"),
    credit: "Mike Cox on Unsplash",
    name: "mike-cox-fj0p1NDAQHA-unsplash",
    label: "neutral",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./image-labeling/neutral/mike-cox-fj0p1NDAQHA-unsplash.jpg"),
    credit: "Mike Cox on Unsplash",
    name: "mike-cox-fj0p1NDAQHA-unsplash",
    label: "neutral",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./image-labeling/borderline-sfw/giorgio-trovato-Mp_DSU6p8cA-unsplash.jpg"),
    credit: "Giorgio Trovata on Unsplash",
    name: "giorgio-trovato-Mp_DSU6p8cA-unsplash",
    label: "borderline-sfw",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./image-labeling/borderline-sfw/alora-griffiths-JNeYWQncbj8-unsplash.jpg"),
    credit: "Alora Griffiths on Unsplash",
    name: "alora-griffiths-JNeYWQncbj8-unsplash",
    label: "borderline-sfw",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/borderline-sfw/christopher-campbell-XrTIFBsZxaY-unsplash.jpg"),
    credit: "Christopher Campbell on Unsplash",
    name: "christopher-campbell-XrTIFBsZxaY-unsplash",
    label: "borderline-sfw",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./image-labeling/borderline-sfw/norbert-buduczki-qYn2Z55Glds-unsplash.jpg"),
    credit: "Norbert Buduczki on Unsplash",
    name: "norbert-buduczki-qYn2Z55Glds-unsplash",
    label: "borderline-sfw",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./image-labeling/borderline-sfw/alora-griffiths-TTrTW-pFxKw-unsplash.jpg"),
    credit: "Alora Griffiths on Unsplash",
    name: "alora-griffiths-TTrTW-pFxKw-unsplash",
    label: "borderline-sfw",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/borderline-sfw/lacey-williams-wVwONOBpUOk-unsplash.jpg"),
    credit: "Lacey Williams on Unsplash",
    name: "lacey-williams-wVwONOBpUOk-unsplash",
    label: "borderline-sfw",
    licensePlate: false,
    face: true,
  },
  {
    image: require("./image-labeling/borderline-sfw/jernej-graj-uvQAdJEamgc-unsplash.jpg"),
    credit: "Jernej Graj on Unsplash",
    name: "jernej-graj-uvQAdJEamgc-unsplash",
    label: "borderline-sfw",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/drawing/64d18f22bd4dfae30b7ea399_astro.jpg"),
    credit: "Transhumans.xyz",
    name: "64d18f22bd4dfae30b7ea399_astro",
    label: "drawing",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/drawing/undraw_coffee_with_friends_3cbj.jpg"),
    credit: "Undraw.co",
    name: "undraw_coffee_with_friends_3cbj",
    label: "drawing",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/drawing/Le_pain_et_les_oeufs_par_Paul_Cezanne.jpg"),
    credit: "Paul Cézanne",
    name: "Le_pain_et_les_oeufs_par_Paul_Cezanne",
    label: "neutral",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/drawing/boston-public-library-6b2xPLPN6ag-unsplash.jpg"),
    credit: "Boston Public Library on Unsplash",
    name: "boston-public-library-6b2xPLPN6ag-unsplash",
    label: "drawing",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/drawing/boston-public-library-_f9cP4_unmg-unsplash.jpg"),
    credit: "Boston Public Library on Unsplash",
    name: "boston-public-library-_f9cP4_unmg-unsplash",
    label: "drawing",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./image-labeling/drawing/europeana-MvR30qxn-MM-unsplash.jpg"),
    credit: "Europeana on Unsplash",
    name: "europeana-MvR30qxn-MM-unsplash.jpg",
    label: "drawing",
    licensePlate: false,
    face: false,
  },
  {
    image: require("./license-plate/bereczki-domokos-zqxrQ2-jFoo-unsplash.jpg"),
    credit: "Bereczki Domokos on Unsplash",
    name: "bereczki-domokos-zqxrQ2-jFoo-unsplash",
    label: "neutral",
    licensePlate: true,
    face: false,
  },
  {
    image: require("./license-plate/campbell-3ZUsNJhi_Ik-unsplash.jpg"),
    credit: "Campbell on Unsplash",
    name: "campbell-3ZUsNJhi_Ik-unsplash",
    label: "neutral",
    licensePlate: true,
    face: false,
  },
  {
    image: require("./license-plate/mick-haupt-elLAOzK9nqU-unsplash.jpg"),
    credit: "Mick Haupt on Unsplash",
    name: "mick-haupt-elLAOzK9nqU-unsplash",
    label: "neutral",
    licensePlate: true,
    face: false,
  },
  {
    image: require("./license-plate/nicholas-byrne-yX_zbwhKWTs-unsplash.jpg"),
    credit: "Nicholas Byrne on Unsplash",
    name: "nicholas-byrne-yX_zbwhKWTs-unsplash",
    label: "neutral",
    licensePlate: true,
    face: false,
  },
  {
    image: require("./license-plate/robert-locke-D199s7KvGvk-unsplash.jpg"),
    credit: "Robert Locke on Unsplash",
    name: "robert-locke-D199s7KvGvk-unsplash",
    label: "neutral",
    licensePlate: true,
    face: false,
  },
  {
    image: require("./license-plate/samuel-foster-LY5eeEO4Mdg-unsplash.jpg"),
    credit: "Samuel Foster on Unsplash",
    name: "samuel-foster-LY5eeEO4Mdg-unsplash",
    label: "neutral",
    licensePlate: true,
    face: false,
  },
  {
    image: require("./object-detection/nevada-plate.jpg"),
    name: "nevada-plate",
    label: "neutral",
    licensePlate: true,
    face: false,
  },
  {
    image: require("./object-detection/arnel-hasanovic-MNd-Rka1o0Q-unsplash.jpg"),
    credit: "Photo by Arnel Hasanovic on Unsplash",
    name: "arnel-hasanovic-MNd-Rka1o0Q-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },
  {
    image: require("./object-detection/brooke-lark-HlNcigvUi4Q-unsplash.jpg"),
    credit: "Photo by Brooke Lark on Unsplash",
    name: "brooke-lark-HlNcigvUi4Q-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },
  {
    image: require("./object-detection/david-lezcano-NfZiOJzZgcg-unsplash.jpg"),
    credit: "Photo by David Lezcano on Unsplash",
    name: "david-lezcano-NfZiOJzZgcg-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },
  {
    image: require("./object-detection/grovemade-RvPDe41lYBA-unsplash.jpg"),
    credit: "Photo by Grovemade on Unsplash",
    name: "grovemade-RvPDe41lYBA-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },

  {
    image: require("./object-detection/jakub-kapusnak-4hgYULBzVEE-unsplash.jpg"),
    credit: "Photo by Jakub Kapusnak on Unsplash",
    name: "jakub-kapusnak-4hgYULBzVEE-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },
  {
    image: require("./object-detection/laurentiu-morariu-OHr6-savxDc-unsplash.jpg"),
    credit: "Photo by Laurentiu Morariu on Unsplash",
    name: "laurentiu-morariu-OHr6-savxDc-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },
  {
    image: require("./object-detection/marcin-nowak-iXqTqC-f6jI-unsplash.jpg"),
    credit: "Photo by Marcin Nowak on Unsplash",
    name: "marcin-nowak-iXqTqC-f6jI-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },
  {
    image: require("./object-detection/sidekix-media-l6u4GIKvxBs-unsplash.jpg"),
    credit: "Photo by Sidekix Media on Unsplash",
    name: "sidekix-media-l6u4GIKvxBs-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },
  {
    image: require("./object-detection/tu-tu-QZGQO3NvsLo-unsplash.jpg"),
    credit: "Photo by Tu Tu on Unsplash",
    name: "tu-tu-QZGQO3NvsLo-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },
  {
    image: require("./object-detection/windows-YzLMmxDTrvI-unsplash.jpg"),
    credit: "Photo by Windows on Unsplash",
    name: "windows-YzLMmxDTrvI-unsplash",
    label: "neutral",
    licensePlate: false,
    face: false,
    knownObject: true,
  },
]
